version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: spotlessCheck
          command: ./gradlew spotlessCheck
      - run:
          name: publish
          command: ./gradlew publish